repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_trivy
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
