---
name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    uses: adam-domagala/workflows/.github/workflows/release.yaml@v1.0.0
    secrets:
      SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
